appVersion: 8.6.1
description: One of the most versatile open source content management systems.
engine: gotpl
home: http://www.drupal.org/
icon: https://bitnami.com/assets/stacks/drupal/img/drupal-stack-220x234.png
keywords:
- drupal
- cms
- blog
- http
- web
- application
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: drupal-demo
sources:
- https://github.com/bitnami/bitnami-docker-drupal
version: 3.1.4
